<a href="https://colab.research.google.com/github/DeuklyoungKo/PytorchBeginnerForDeepLearning/blob/main/chap02_01_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x=.5
y=1.2
z=2.4
y+z

3.5999999999999996

In [5]:
a = {"class":["deep learning","machine learning"], "num_students":[40,20]}
print(a)
print(type(a))

{'class': ['deep learning', 'machine learning'], 'num_students': [40, 20]}
<class 'dict'>


In [7]:
a["class"]

['deep learning', 'machine learning']

In [8]:
a['gade']=['A','B','C']
a

{'class': ['deep learning', 'machine learning'],
 'gade': ['A', 'B', 'C'],
 'num_students': [40, 20]}

In [9]:
a.keys()

dict_keys(['class', 'num_students', 'gade'])

In [10]:
list(a.keys())

['class', 'num_students', 'gade']

In [11]:
a.values()

dict_values([['deep learning', 'machine learning'], [40, 20], ['A', 'B', 'C']])

In [13]:
list(a.values())

[['deep learning', 'machine learning'], [40, 20], ['A', 'B', 'C']]

In [12]:
a.items()

dict_items([('class', ['deep learning', 'machine learning']), ('num_students', [40, 20]), ('gade', ['A', 'B', 'C'])])

In [24]:
import numpy as np

d = np.arange(10)
print(d)
print(d.shape)

x1 = d.reshape(1,10)
print(x1)
print(x1.shape)

x2 = d.reshape(2,5)
print(x2)
print(x2.shape)

x3 = d.reshape(2,-1)
print(x3)
print(x3.shape)

x4 = d.reshape(5,-1)
print(x4)
print(x4.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [26]:
mu = 0
sigma = 1
arr = np.random.normal(mu, sigma, (5,3))
arr

array([[ 0.40484605,  0.10922397,  0.40968963],
       [-2.1310764 , -1.59754644, -1.16790239],
       [-1.33477696, -1.63809097, -0.61294149],
       [ 0.11575869, -0.13698506, -1.57643777],
       [ 0.02770553,  1.73851312,  1.15439069]])

In [27]:
np.where(abs(arr) > sigma, "out", "in")

array([['in', 'in', 'in'],
       ['out', 'out', 'out'],
       ['out', 'out', 'in'],
       ['in', 'in', 'out'],
       ['in', 'out', 'out']], dtype='<U3')

In [29]:
x = np.where(abs(arr) > sigma)
x

(array([1, 1, 1, 2, 2, 3, 4, 4]), array([0, 1, 2, 0, 1, 2, 1, 2]))

In [33]:
a = np.array([[1,3],[0,-1]])
b = np.random.randint(0,10,4).reshape(2,2)
print("a=",a)
print("b=",b)
a+b

a= [[ 1  3]
 [ 0 -1]]
b= [[3 8]
 [8 5]]


array([[ 4, 11],
       [ 8,  4]])

In [37]:
print(a*b)
print(a**b)
print(np.matmul(a,b))

[[ 3 24]
 [ 0 -5]]
[[   1 6561]
 [   0   -1]]
[[27 23]
 [-8 -5]]


In [41]:
print(np.concatenate([a,b], axis=0))
print(np.vstack((a,b)))
print(np.concatenate([a,b], axis=1))
print(np.hstack((a,b)))


[[ 1  3]
 [ 0 -1]
 [ 3  8]
 [ 8  5]]
[[ 1  3]
 [ 0 -1]
 [ 3  8]
 [ 8  5]]
[[ 1  3  3  8]
 [ 0 -1  8  5]]
[[ 1  3  3  8]
 [ 0 -1  8  5]]


In [42]:
z = np.random.randint(0,2,(2,3))
z

array([[1, 1, 0],
       [0, 1, 1]])