<a href="https://colab.research.google.com/github/DeuklyoungKo/PytorchBeginnerForDeepLearning/blob/main/chap02_02_pythonClass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

class DataPreprocessing:

  def __init__(self, data, target):
    self.data = data
    self.target = target
    self.num_instances = self.data.shape[0]
    self.num_features = self.data.shape[1]

  def minmax(self):
    for i in range(self.num_features):
      col = self.data[:,i]
      self.data[:,i] = (self.data[:,i]-np.min(col))/(np.max(col)-np.min(col))
    return self

  def normalization(self):
    for i in range(self.num_features):
      col = self.data[:,i]
      mu, sigma = np.mean(col), np.std(col)
      self.data[:,]=(self.data[:,i]-mu)/sigma
    return self

  def scaler(self, scaling=None):
    if scaling == 'minmax':
      self.minmax()
    elif scaling == 'stardard':
      self.normalization()
    else:
      pass
    return self.data

In [7]:
data = np.random.normal(0,10,(5,5))
target = np.random.normal(0,1,5)
print(data)
data_processor = DataPreprocessing(data, target)
data = data_processor.scaler('minmax')
print(data)

[[  6.87841026   5.51718913  -1.41079692 -10.5569801   14.16038051]
 [  2.2246707   -2.31521172 -12.27443223  13.80907128 -11.75912119]
 [  3.69719284   0.38775681  10.80230548   6.22934094 -12.8060595 ]
 [  9.36256025   3.87382765  -6.82197675  -6.53930474   7.97874373]
 [ 25.59526717  -9.72062298   5.8701224    3.44557594   5.15911075]]
[[0.19912798 1.         0.47076131 0.         1.        ]
 [0.         0.48598914 0.         1.         0.03882375]
 [0.06300747 0.66337475 1.         0.6889225  0.        ]
 [0.3054218  0.8921524  0.23627497 0.16488824 0.77076556]
 [1.         0.         0.78627035 0.57467481 0.66620474]]


In [11]:
class DataPipeline(DataPreprocessing):
  def __init__(self, data):
    self.data = data
    self.num_features = self.data.shape[1]
pipe = DataPipeline(data)
data = pipe.scaler('minmax')
data

array([[0.19912798, 1.        , 0.47076131, 0.        , 1.        ],
       [0.        , 0.48598914, 0.        , 1.        , 0.03882375],
       [0.06300747, 0.66337475, 1.        , 0.6889225 , 0.        ],
       [0.3054218 , 0.8921524 , 0.23627497, 0.16488824, 0.77076556],
       [1.        , 0.        , 0.78627035, 0.57467481, 0.66620474]])