<a href="https://colab.research.google.com/github/DeuklyoungKo/PytorchBeginnerForDeepLearning/blob/main/chap04_01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

x = torch.rand(8,8)
print(x.size())

torch.Size([8, 8])


In [3]:
a = x.view(64)
print(x.size())
print(a.size())
print(a)

torch.Size([8, 8])
torch.Size([64])
tensor([0.7062, 0.7037, 0.9210, 0.5862, 0.0632, 0.4968, 0.9335, 0.0047, 0.0619,
        0.0153, 0.7637, 0.8076, 0.3551, 0.5193, 0.5647, 0.7885, 0.0200, 0.4287,
        0.1295, 0.0338, 0.7406, 0.2380, 0.9807, 0.5156, 0.6644, 0.1305, 0.5276,
        0.3260, 0.8892, 0.2840, 0.8532, 0.6731, 0.3730, 0.4671, 0.6970, 0.4356,
        0.6359, 0.3776, 0.9581, 0.7579, 0.1215, 0.1125, 0.3968, 0.1056, 0.3202,
        0.3962, 0.6624, 0.6009, 0.9409, 0.6813, 0.2275, 0.6339, 0.8743, 0.8682,
        0.6359, 0.7893, 0.5894, 0.8968, 0.8993, 0.6984, 0.5863, 0.3736, 0.8560,
        0.4860])


In [5]:
b = x.view(-1,4,4) # -1은 원래 크기가 되게 하는 값 8x8 -> -1x4x4 즉, 4x4x4이다.
print(b.size())
print(b)

torch.Size([4, 4, 4])
tensor([[[0.7062, 0.7037, 0.9210, 0.5862],
         [0.0632, 0.4968, 0.9335, 0.0047],
         [0.0619, 0.0153, 0.7637, 0.8076],
         [0.3551, 0.5193, 0.5647, 0.7885]],

        [[0.0200, 0.4287, 0.1295, 0.0338],
         [0.7406, 0.2380, 0.9807, 0.5156],
         [0.6644, 0.1305, 0.5276, 0.3260],
         [0.8892, 0.2840, 0.8532, 0.6731]],

        [[0.3730, 0.4671, 0.6970, 0.4356],
         [0.6359, 0.3776, 0.9581, 0.7579],
         [0.1215, 0.1125, 0.3968, 0.1056],
         [0.3202, 0.3962, 0.6624, 0.6009]],

        [[0.9409, 0.6813, 0.2275, 0.6339],
         [0.8743, 0.8682, 0.6359, 0.7893],
         [0.5894, 0.8968, 0.8993, 0.6984],
         [0.5863, 0.3736, 0.8560, 0.4860]]])


In [14]:
x = torch.rand(8,8)
y = x.numpy()
print(type(y))
print(x)
print(y)






<class 'numpy.ndarray'>
tensor([[0.4159, 0.4371, 0.6022, 0.6075, 0.0825, 0.0086, 0.3129, 0.0455],
        [0.4775, 0.7944, 0.7658, 0.0741, 0.4404, 0.6189, 0.7995, 0.3433],
        [0.9642, 0.1550, 0.6923, 0.8379, 0.5133, 0.4165, 0.6130, 0.8734],
        [0.2583, 0.2441, 0.1172, 0.5304, 0.7250, 0.2223, 0.0914, 0.0778],
        [0.1523, 0.2750, 0.2194, 0.7184, 0.4391, 0.2738, 0.7777, 0.2538],
        [0.6751, 0.3353, 0.2544, 0.1140, 0.5102, 0.2138, 0.9678, 0.6076],
        [0.6768, 0.0183, 0.3528, 0.7605, 0.0790, 0.4618, 0.9156, 0.4311],
        [0.5073, 0.4952, 0.3927, 0.9317, 0.6146, 0.4495, 0.6511, 0.1058]])
[[0.41588163 0.43706262 0.6021721  0.60745615 0.08252668 0.00863439
  0.31294662 0.04553467]
 [0.47749364 0.79440266 0.7658294  0.07411289 0.44041795 0.6188508
  0.79947394 0.34327608]
 [0.96422666 0.15500051 0.69225883 0.8378537  0.5133326  0.4164517
  0.61302835 0.8733965 ]
 [0.2582876  0.24410892 0.11716467 0.53041923 0.7249917  0.22225022
  0.09141111 0.07775313]
 [0.15227735 

In [18]:
z = [1,2,3,4]
print(type(z))
t = torch.tensor(z)
print(t)

print(t.numpy())

<class 'list'>
tensor([1, 2, 3, 4])
[1 2 3 4]
